### ISSUE TITLE
Dropped 21/21 stack traces because of errors / Failed to copy memory address 0

### ISSUE THREAD

**Issue by jfirebaugh** [rbspy/rbspy#370]
With a particular combination of gems, I get the following output from rbspy 0.12.1:

```
rbspy is recording traces. Press Ctrl+C to stop.
Dropped 21/21 stack traces because of errors. Please consider reporting a GitHub issue -- this isn't normal.
Warning: no profile samples were collected
Wrote raw data to /Users/john/Library/Caches/rbspy/2022-09-16-P1QnakSghm.raw.gz
Wrote formatted output to /Users/john/Library/Caches/rbspy/2022-09-16-IOCishdwar.flamegraph.svg
Something went wrong while rbspy was sampling the process. Here's what we know:
- Failed to copy memory address 0
```

Minimal repro: https://github.com/jfirebaugh/rbspy_bug

It's not 100% reproducible, so if it doesn't show up on the first run, try a half-dozen or so times.

Ruby version, in case it's relevant:

```
ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
```

**Comment by pwoolcoc** [comment]
I'm seeing the same bug

**Comment by acj** [comment]
@pwoolcoc Yes, process startup is a tricky thing for rbspy to handle. There are internal sleeps and retries to deal with this, but it doesn't always work. If you're up for building from source, the startup code in `main` has changed and might be more reliable for you. If not, your sleep workaround is what I'd recommend. (Also, hello from a fellow Michigander. :-)

@jfirebaugh Thanks for the example repo. I'm actually able to repro the error with a zero-dependency Gemfile, which makes me wonder if this is related to bundler somehow, or maybe recent macOS updates. The error also happens on examples that used to work for me. I'll look into it. Can you share which version of bundler and macOS you're using?

**Comment by jfirebaugh** [comment]
Thanks @acj. Bundler 2.2.32 on macOS 12.5.1.

**Comment by acj** [comment]
I think this is fixed in 0.13.0 (just released). Please give it a try.

**Comment by jfirebaugh** [comment]
It's still not working for me, but with a different error. I'll open a new issue.
